"""
Task 3: High-Level to Low-Level Architecture Pipeline
Main entry point — orchestrates the full pipeline:
1. Accept a high-level business requirement (text input)
2. Analyze and break it into modules
3. Generate database schemas for each module
4. Generate pseudocode for core logic
5. Generate a REST API spec
6. Output a complete technical_spec.md
"""

import os
import sys
from dotenv import load_dotenv
load_dotenv()  # Must be called before importing modules that read env vars at module level
from analyzer import analyze_requirements
from module_generator import generate_modules
from schema_generator import generate_schemas
from pseudocode_gen import generate_pseudocode
from api_generator import generate_api_spec

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "outputs")

SAMPLE_REQUIREMENT = """
Build an online food delivery platform where customers can browse restaurants, 
place orders, track deliveries in real-time, and make payments online. 
Restaurant owners should be able to manage their menus and view order history. 
Delivery agents should receive order assignments and update delivery status.
"""


def run_pipeline(requirement: str = None) -> None:
    """
    Run the full high-level to low-level architecture pipeline.

    Args:
        requirement: Business requirement string. Defaults to SAMPLE_REQUIREMENT.
    """
    print("=" * 65)
    print("   High-Level → Low-Level Architecture Pipeline")
    print("=" * 65)

    if not requirement:
        print("\n  No requirement provided. Using built-in sample requirement.")
        requirement = SAMPLE_REQUIREMENT

    print(f"\n[Input Requirement]\n{requirement.strip()}\n")
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Step 1: Analyze the requirement
    print("─" * 65)
    print("[Step 1] Analyzing business requirements...")
    analysis = analyze_requirements(requirement)
    print(f"  Entities identified  : {', '.join(analysis['entities'])}")
    print(f"  Core features        : {', '.join(analysis['features'])}")
    print(f"  Non-functional needs : {', '.join(analysis['non_functional'])}")

    # Step 2: Generate modules
    print("\n[Step 2] Generating system modules...")
    modules = generate_modules(analysis)
    print(f"  Modules created      : {len(modules)}")
    for m in modules:
        print(f"    • {m['name']}: {m['description']}")

    # Step 3: Generate schemas
    print("\n[Step 3] Generating database schemas...")
    schemas = generate_schemas(modules, analysis["entities"])
    print(f"  Schemas generated    : {len(schemas)} table(s)")

    # Step 4: Generate pseudocode
    print("\n[Step 4] Generating pseudocode for core logic...")
    pseudocode = generate_pseudocode(modules)
    print(f"  Pseudocode blocks    : {len(pseudocode)}")

    # Step 5: Generate API spec
    print("\n[Step 5] Generating REST API specification...")
    api_spec = generate_api_spec(modules)
    print(f"  API endpoints        : {len(api_spec['endpoints'])}")

    # Step 6: Write technical_spec.md
    print("\n[Step 6] Writing technical specification document...")
    spec_path = os.path.join(OUTPUT_DIR, "technical_spec.md")
    _write_spec(spec_path, requirement, analysis, modules, schemas, pseudocode, api_spec)
    print(f"  Saved to             : outputs/technical_spec.md")

    print("\n" + "=" * 65)
    print("   Pipeline completed! Review outputs/technical_spec.md")
    print("=" * 65)


def _write_spec(
    path: str,
    requirement: str,
    analysis: dict,
    modules: list,
    schemas: list,
    pseudocode: list,
    api_spec: dict,
) -> None:
    """Combine all pipeline outputs into a single Markdown spec document."""
    lines = []

    lines.append("# Technical Specification Document\n")
    lines.append(f"> Auto-generated by the High-Level → Low-Level Architecture Pipeline\n")

    lines.append("---\n")
    lines.append("## 1. Business Requirement\n")
    lines.append(f"{requirement.strip()}\n")

    lines.append("---\n")
    lines.append("## 2. Requirement Analysis\n")
    lines.append(f"**Core Entities:** {', '.join(analysis['entities'])}\n")
    lines.append(f"**Key Features:** {', '.join(analysis['features'])}\n")
    lines.append(f"**Non-Functional Requirements:** {', '.join(analysis['non_functional'])}\n")

    lines.append("---\n")
    lines.append("## 3. System Modules\n")
    for m in modules:
        lines.append(f"### {m['name']}\n")
        lines.append(f"**Description:** {m['description']}\n")
        lines.append(f"**Responsibilities:**\n")
        for r in m.get("responsibilities", []):
            lines.append(f"- {r}\n")
        lines.append("\n")

    lines.append("---\n")
    lines.append("## 4. Database Schemas\n")
    for schema in schemas:
        lines.append(f"### Table: `{schema['table']}`\n")
        lines.append("| Column | Type | Constraints |\n")
        lines.append("|--------|------|-------------|\n")
        for col in schema["columns"]:
            lines.append(f"| {col['name']} | {col['type']} | {col.get('constraints', '')} |\n")
        lines.append("\n")

    lines.append("---\n")
    lines.append("## 5. Pseudocode\n")
    for block in pseudocode:
        lines.append(f"### {block['module']}: {block['function']}\n")
        lines.append("```\n")
        lines.append(block["code"] + "\n")
        lines.append("```\n\n")

    lines.append("---\n")
    lines.append("## 6. REST API Specification\n")
    lines.append(f"**Base URL:** `{api_spec['base_url']}`\n\n")
    for ep in api_spec["endpoints"]:
        lines.append(f"#### `{ep['method']} {ep['path']}`\n")
        lines.append(f"- **Description:** {ep['description']}\n")
        lines.append(f"- **Auth Required:** {ep.get('auth', 'Yes')}\n")
        if ep.get("request_body"):
            lines.append(f"- **Request Body:** `{ep['request_body']}`\n")
        lines.append(f"- **Response:** `{ep['response']}`\n\n")

    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)


if __name__ == "__main__":
    user_req = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else None
    run_pipeline(user_req)
